name: Metrics

on:
  # schedule:
  #   - cron: '* */24 * * *'
  push:
    branches:
      - feat/useMetrics
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # See all supported options
          # https://github.com/lowlighter/metrics/blob/4eeea4c0cd385c2c0a8d56c6b03b6484f8c61bdd/action.yml
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://jpsern.com
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip:  
          plugin_habits: yes
          plugin_introduction: yes
          plugin_followup: yes
